{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ios-plus.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ios-plus.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.secrets.vaultAgentInjection }}
    vault.hashicorp.com/role: {{ .Values.secrets.vaultRole | quote }}
  {{- end }}
{{- end }}
