apiVersion: v1
kind: ServiceAccount
metadata:
  name: ios-plus-sa
  namespace: {{ .Values.global.namespace }}
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "ios-plus"
