export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const ERROR_CODES = {
  COMPLIANCE_DENIED: 'COMPLIANCE_DENIED',
  COMPLIANCE_ESCALATION: 'COMPLIANCE_ESCALATION',
  EVIDENCE_INVALID: 'EVIDENCE_INVALID',
  EVIDENCE_VERIFICATION_FAILED: 'EVIDENCE_VERIFICATION_FAILED',
  AUDIT_WRITE_FAILURE: 'AUDIT_WRITE_FAILURE',
  AUDIT_WORM_VIOLATION: 'AUDIT_WORM_VIOLATION',
  UNAUTHORIZED: 'UNAUTHORIZED',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RETRIEVAL_PARTITION_NOT_FOUND: 'RETRIEVAL_PARTITION_NOT_FOUND',
  TRANSPORT_TIMEOUT: 'TRANSPORT_TIMEOUT',
  POLICY_NOT_FOUND: 'POLICY_NOT_FOUND',
} as const;

export const PACKAGE_CONSTANTS = {
  VERSION: '1.0.0',
  NAME: '@ios-plus/shared',
  DEFAULT_TIMEOUT_MS: 30000,
  MAX_RETRIES: 3,
  AUDIT_RETENTION_DAYS: 2555,
  WORM_LOCK_DAYS: 30,
} as const;
